src/components/button/Button.tsx, src/components/form/item/ItemForm.tsx, src/components/item-sidebars/ShowItemSidebar.tsx, src/components/sidebar/Sidebar.tsx
- Fixed the button in the AddItemSidebar and ShowItemSidebar
- Add some classes to add some hover effect to Button component
closes #37
=> FIX: Need to update the cancel button in the addItemSidebar

src/components/button/Button.tsx, src/components/cards/Item.tsx, src/components/form/item/ItemForm.tsx, src/components/item-sidebars/ShowItemSidebar.tsx, src/components/sidebar/Sidebar.tsx, src/pages/items/ItemsPage.tsx
- Replaced the grid system by a flex one
- Modified the css in the Item component
closes #38
=> FIX: Change the grid in the items page for a flex system

src/components/navbar/Navbar.tsx, src/components/shopping-basket/ShoppingBasket.tsx
=> Refactor shopping basket

src/components/add-item/AddNewItem.tsx, src/components/categories/CategoryTitle.tsx, src/pages/items/ItemsPage.tsx, src/types/items/types.tsx, tailwind.config.js
=> FEAT: Edit category name

src/App.tsx, src/components/form-elements/SearchInput.tsx, src/pages/items/ItemsPage.tsx
=> FEAT: Add search items component

package.json, src/components/navbar/Navbar.tsx, yarn.lock
=> FEAT: Add Tooltip for the navbar 

src/components/form/item/ItemForm.tsx, src/pages/items/ItemsPage.tsx, src/types/items/types.tsx
=> FEAT: If no items are present in category

src/pages/history/HistoryPage.tsx
=> FIX: History page

src/components/form/item/ItemForm.tsx
=> FIX: add enableReinitialize to reset the initialValues

src/components/form/item/ItemForm.tsx, src/components/sidebar/Sidebar.tsx
=> FIX: change the way the sidebar history works

src/components/cards/Item.tsx, src/components/shopping-basket/ShoppingBasket.tsx, src/components/shopping-list/shopping-list__item/ShoppingListItem.tsx, src/components/shopping-list/shopping-list__main/ShoppingList.tsx, src/global-state/miscState.tsx, src/global-state/shopListState.tsx, src/pages/history/HistoryPage.tsx, src/types/state/appConfigTypes.ts, src/types/state/shoppingListTypes.ts
=> Handle status change history page refresh data

src/pages/items/ItemsPage.tsx
I had a couple of imports problem with the pull request I just merge. It seems to work again.
=> FIX: fix the imports problem

src/components/item-sidebars/AddItemSidebar.tsx, src/components/item-sidebars/ShowItemSidebar.tsx, src/components/shopping-list/shopping-list__main/ShoppingList.tsx, src/components/shopping-list/shopping-list__main/ShoppingListStatusModal.tsx, src/components/sidebar/Sidebar.tsx
I made some quick modifications and add some classes to adjust how the overflow works and delete the fixed modal in the bottom as it is not needed with the use of flexbox.
=> FEAT: Change shopping list style

package.json, src/components/form-elements/SearchInput.tsx, yarn.lock
Add the debounceInput library to handle the search of the items. I'm not sure if it's better or not? So don't merge it if you're not convinced. It's more experimentation ;)
=> FIX: Add DebounceInput library

src/components/shopping-list/shopping-list__main/ShoppingList.tsx
Closes #86 
Test with data@test.com account
=> Fix sticky issue

package.json, src/components/categories/CategoryTitle.tsx, src/components/content/ContentEditable.tsx, src/components/shopping-list/shopping-list__main/ShoppingListTitle.tsx, yarn.lock
As far as I tested works ok. I didn't pay too much attention to styling just the functionality, so some styles might be 'broken' :D
Closes #85
=> Issue#85 refactor editable field

src/components/form-elements/CategorySelect.tsx
=> FIX: update the autoComplete and fix the uncontrolled input error

src/components/cards/Item.tsx, src/components/item-sidebars/ShowItemSidebar.tsx, src/components/loader/BasicLoader.tsx, src/index.tsx, src/pages/history/HistoryPage.tsx, src/pages/history/HistoryShowPage.tsx, src/styles/styles.css
=> FEAT: Add loader and no list in history page

package.json, src/App.tsx, src/components/cards/Item.tsx, src/components/categories/CategoryTitle.tsx, src/components/form/auth/LoginForm.tsx, src/components/form/auth/RegisterForm.tsx, src/components/heading/CategoryHeading.tsx, src/components/heading/CategoryHeadingEditable.tsx, src/components/item-sidebars/ShowItemSidebar.tsx, src/components/route/PrivateRoute.tsx, src/components/shopping-list/shopping-list__main/RenderShopList.tsx, src/global-state/categoriesState.tsx, src/hooks/useFetchCategories.tsx, src/index.tsx, src/pages/items/ItemsPage.tsx, yarn.lock
=> Fix performances when updating a category and dispatch the update to the sidebar and shoppingList

src/App.tsx, src/components/form-elements/CategorySelect.tsx, src/components/form/item/ItemForm.tsx, src/components/item-sidebars/ShowItemSidebar.tsx, src/global-state/categoriesState.tsx, src/hooks/useFetchCategories.tsx, src/hooks/useFetchItems.tsx, src/pages/items/ItemsPage.tsx
There was an issue while loading the shopping list and the items when the categories were not loaded. 
I hope this PR fix completely the issue.
=> FIX: Fix the issue with the categories not loaded

src/components/content/ContentEditable.tsx, src/components/heading/CategoryHeadingEditable.tsx
On category heading save trim title and remove double or more spaces between words.
=> Issue#122 content editable

src/components/item-sidebars/ShowItemSidebar.tsx, src/components/shopping-list/shopping-list__item/ShoppingListItem.tsx, src/global-state/shopListState.tsx, src/hooks/useAddItemToShopList.tsx, src/hooks/useCreateNewShoppingList.tsx, src/hooks/useLoadActiveListData.tsx
=> Issue#120 quantity item

src/components/cards/Item.tsx, src/components/cards/List.tsx, src/types/items/types.tsx
Add deleted_at column to the ItemType ( also added from the backend response of course )
Add some basic classes to the Item.tsx to show when the item has been deleted. 
closes #127
=> FIX: Show in history page when an item is deleted

package.json, src/components/heading/CategoryHeadingEditable.tsx, src/pages/history/HistoryShowPage.tsx, yarn.lock
=> FIX: Always show the edit category button on mobile and tablet

src/App.tsx, src/components/button/AddItemButton.tsx, src/components/form-elements/CategorySelect.tsx, src/components/form/item/ItemForm.tsx, src/components/item-sidebars/ShowItemSidebar.tsx, src/pages/items/ItemsPage.tsx
- Fix the issue when the categoryName was not updated when we wanted to add a new Item.
- Update the shoppingList ( re-fetch actually ) when an item is updated/deleted
closes #133
=> Problem when we add an item with a new category and when an item is updated/deleted

src/components/shopping-list/shopping-list__main/ShoppingListTitle.tsx
=> Add enter press callback

src/components/item-sidebars/ShowItemSidebar.tsx
=> FEAT: Add a random image if the current image cannot be loaded

src/hooks/useInfiniteScroll.tsx, src/pages/items/ItemsPage.tsx
I reworked on the performance issues when a user has a lot of data. Try it and tell me if you find the behavior ok ;).
=> FIX: Rework on the performance issue with a lot of data

src/components/form-elements/Checkbox.tsx, src/components/shopping-list/shopping-list__item/ShoppingListItem.tsx, src/styles/styles.css, tailwind.config.js
=> Style checkbox in shop list

src/global-state/shopListHistoryState.tsx, src/hooks/useFetchHistoryLists.tsx, src/pages/history/HistoryPage.tsx
=> FIX: display only one scrollbar and add loading state

src/components/cards/Item.tsx, src/pages/history/HistoryShowPage.tsx, src/pages/items/ItemsPage.tsx
=> FIX: change grid to 1 column in xs and modify the deleted state of an item

src/components/stats/Progress.tsx, src/components/stats/StatsListing.tsx, src/styles/styles.css
=> FIX: Fix progress style in firefox

src/components/errors/BasicError.tsx, src/components/form/item/ItemForm.tsx, src/components/item-sidebars/ShowItemSidebar.tsx, src/global-state/itemsState.tsx, src/pages/history/HistoryShowPage.tsx
=> FIX: Update the list in the HistoryShowPage when we update or delete an item

src/components/item-sidebars/ShowItemSidebar.tsx, src/pages/items/ItemsPage.tsx
I tried different positions/colors for the button but if you have other ideas, feel free to modify the emplacement/style.
closes #135
=> FEAT: Add button to add a new item on the ItemShowSidebar

src/components/content/ContentEditable.tsx, src/components/heading/CategoryHeadingEditable.tsx
=> FIX: fix the issue when pressing enter after updating a category name

src/components/navbar/UserMenu.tsx, src/components/shopping-basket/ShoppingBasket.tsx, src/components/shopping-list/shopping-list__main/RenderShopList.tsx, src/components/shopping-list/shopping-list__main/ShoppingList.tsx, src/global-state/shopListState.tsx, src/hooks/useLoadActiveListData.tsx, tailwind.config.js
=> FIX: add loading state for the active list and for the shopping basket

src/index.html, tailwind.config.js, webpack.config.js
=> FIX: add purge to tailwind
